/**
 * Phase 12 Part D (D0) — the i18n layer, pure.
 *
 * gettext style: the ENGLISH string in the source is the key. `t("Review
 * drafts")` returns "Review drafts" in English and the catalogue's value in
 * any other locale; a key missing from a locale falls back to English, and
 * the per-locale test (tests/utils/i18nCatalogue.test.js) fails on any key
 * present in en and missing in that locale, so a shipped locale is complete
 * by construction. English behaviour is unchanged by construction too: the
 * value for English IS the source string.
 *
 * Interpolation: `{name}` from vars; ICU-lite plurals
 * `{n, plural, one {# draft} other {# drafts}}` where `#` is the number.
 * Dates, numbers and currency go through Intl with the locale.
 *
 * locales/en.json is generated by scripts/i18n-extract.mjs and is the
 * catalogue translators work from; every other locale maps the same keys.
 */
// English is the identity: every value in locales/en.json equals its key, so
// nothing is imported for it and nothing is shipped to the browser for it.
// Each other locale is imported here the day it goes live (~30 KB Polaris +
// the catalogue, per locale — the bundle budget in scripts/check-bundle-budget.mjs
// is raised by that much with a note when one is added).

export const SUPPORTED_UI_LOCALES = Object.freeze(["en", "de", "fr", "es", "it", "pt-BR", "ja"]);

/** Each language in its own name — the one label that is never translated. */
export const UI_LOCALE_NAMES = Object.freeze({ en: "English", de: "Deutsch", fr: "Français", es: "Español", it: "Italiano", "pt-BR": "Português (Brasil)", ja: "日本語" });
export const DEFAULT_UI_LOCALE = "en";

/** Shopify's `locale` param ("fr-FR", "pt-BR", "de") → one of ours, or the default. */
export function normaliseUiLocale(raw) {
  const v = String(raw ?? "").trim();
  if (!v) return DEFAULT_UI_LOCALE;
  const lower = v.toLowerCase();
  if (lower.startsWith("pt")) return "pt-BR";
  const base = lower.split(/[-_]/)[0];
  return SUPPORTED_UI_LOCALES.includes(base) ? base : DEFAULT_UI_LOCALE;
}

/** The translated catalogues that ship. A locale listed in SUPPORTED_UI_LOCALES without a catalogue here is not yet live. */
export const CATALOGUES = Object.freeze({});

export const LIVE_UI_LOCALES = Object.freeze(["en", ...Object.keys(CATALOGUES)]);

const PLURAL_RE = /\{(\w+),\s*plural,\s*((?:=?\w+\s*\{[^{}]*\}\s*)+)\}/g;

function pluralCategory(locale, n) {
  try {
    return new Intl.PluralRules(locale).select(Number(n));
  } catch {
    return Number(n) === 1 ? "one" : "other";
  }
}

/** Fill `{name}` and `{n, plural, …}` in a catalogue value. Pure. */
export function interpolate(value, vars = {}, locale = DEFAULT_UI_LOCALE) {
  let s = String(value ?? "");
  s = s.replace(PLURAL_RE, (_m, name, forms) => {
    const n = vars[name];
    const table = {};
    for (const m of forms.matchAll(/(=?\w+)\s*\{([^{}]*)\}/g)) table[m[1]] = m[2];
    const exact = table[`=${n}`];
    const chosen = exact ?? table[pluralCategory(locale, n)] ?? table.other ?? "";
    return chosen.replace(/#/g, String(n));
  });
  s = s.replace(/\{(\w+)\}/g, (m, name) => (name in vars ? String(vars[name]) : m));
  return s;
}

/** The translation function for a locale. Unknown key → the key itself (it IS the English). */
export function createT(locale = DEFAULT_UI_LOCALE) {
  const loc = LIVE_UI_LOCALES.includes(locale) ? locale : DEFAULT_UI_LOCALE;
  const table = CATALOGUES[loc] ?? null; // null = English, the identity
  const t = (key, vars) => {
    const value = table?.[key] ?? key;
    return vars ? interpolate(value, vars, loc) : value;
  };
  t.locale = loc;
  t.number = (n, opts) => new Intl.NumberFormat(loc, opts).format(n);
  t.date = (d, opts = { day: "numeric", month: "long" }) => new Intl.DateTimeFormat(loc, opts).format(new Date(d));
  t.currency = (amount, currency = "USD") => new Intl.NumberFormat(loc, { style: "currency", currency }).format(amount);
  return t;
}

/** Server side: the locale from a request's URL (the embedded app keeps `locale` sticky). */
export function localeFromRequest(request) {
  try {
    return normaliseUiLocale(new URL(request.url).searchParams.get("locale"));
  } catch {
    return DEFAULT_UI_LOCALE;
  }
}

export const tForRequest = (request) => createT(localeFromRequest(request));

/**
 * Marks a string that lives outside any function (an options table, a plan
 * name) as a catalogue key WITHOUT translating it there — the use site calls
 * t(value) at render time. Identity at runtime; the extractor collects it.
 */
export const T = (s) => s;
export const tFor = (locale) => createT(normaliseUiLocale(locale));
