/**
 * Phase 12 Part D — the i18n layer, pure.
 *
 * gettext style: the ENGLISH string in the source is the key. `t("Review
 * drafts")` returns "Review drafts" in English and the catalogue's value in
 * any other locale; a key missing from a locale falls back to English, and
 * the per-locale test (tests/utils/i18nCatalogue.test.js) fails on any key
 * present in en and missing in that locale, so a shipped locale is complete
 * by construction. English behaviour is unchanged by construction too: the
 * value for English IS the source string.
 *
 * Interpolation: `{name}` from vars; ICU-lite plurals
 * `{n, plural, one {# draft} other {# drafts}}` where `#` is the number.
 * Dates, numbers and currency go through Intl with the locale.
 *
 * locales/en.json is generated by scripts/i18n-extract.mjs and is the
 * catalogue translators work from; every other locale maps the same keys.
 *
 * ── Where a catalogue lives (D1) ───────────────────────────────────────────
 *
 * English is the identity: nothing is imported for it and nothing is shipped
 * to the browser for it. Every other live locale is a REGISTRY entry, filled
 * from two places so the shared client bundle never carries a catalogue:
 *
 *   server   catalogues.server.js imports every live locale statically and
 *            registers it at boot (entry.server.jsx imports that module).
 *   browser  chunks.js holds one lazy `import()` per live locale — Vite
 *            splits each into its own chunk — and entry.client.jsx awaits
 *            the document's locale before hydrating, so the first render
 *            on the client matches the server's. A merchant on English
 *            downloads no catalogue; a merchant on German downloads
 *            German's, once, cached.
 *
 * scripts/check-bundle-budget.mjs measures those locale chunks separately
 * from what every merchant downloads.
 */

export const SUPPORTED_UI_LOCALES = Object.freeze(["en", "de", "fr", "es", "it", "pt-BR", "ja"]);

/** Each language in its own name — the one label that is never translated. */
export const UI_LOCALE_NAMES = Object.freeze({ en: "English", de: "Deutsch", fr: "Français", es: "Español", it: "Italiano", "pt-BR": "Português (Brasil)", ja: "日本語" });
export const DEFAULT_UI_LOCALE = "en";

/**
 * The locales whose catalogue is complete and shipped. A locale is added here
 * the day it goes live, together with locales/<locale>.json, its lazy chunk
 * in chunks.js and its static import in catalogues.server.js —
 * tests/utils/i18nCatalogue.test.js holds the four together.
 *
 *   D1  de  2026-09-15
 *   D2  fr  2026-09-15
 *   D3  es  2026-09-15
 *   D4  it  2026-09-15
 *   D5  pt-BR  2026-09-15
 */
export const LIVE_UI_LOCALES = Object.freeze(["en", "de", "fr", "es", "it", "pt-BR"]);

/** Shopify's `locale` param ("fr-FR", "pt-BR", "de") → one of ours, or the default. */
export function normaliseUiLocale(raw) {
  const v = String(raw ?? "").trim();
  if (!v) return DEFAULT_UI_LOCALE;
  const lower = v.toLowerCase();
  if (lower.startsWith("pt")) return "pt-BR";
  const base = lower.split(/[-_]/)[0];
  return SUPPORTED_UI_LOCALES.includes(base) ? base : DEFAULT_UI_LOCALE;
}

/**
 * A locale from an Accept-Language header, for the public pages (privacy,
 * terms) that have no Shopify param. The first listed language we ship
 * wins; anything else is English.
 */
export function localeFromAcceptLanguage(header) {
  const parts = String(header ?? "")
    .split(",")
    .map((p) => p.trim().split(";")[0])
    .filter(Boolean);
  for (const p of parts) {
    if (/^en\b/i.test(p)) return DEFAULT_UI_LOCALE;
    const loc = normaliseUiLocale(p);
    if (loc !== DEFAULT_UI_LOCALE && LIVE_UI_LOCALES.includes(loc)) return loc;
  }
  return DEFAULT_UI_LOCALE;
}

// ── the registry ───────────────────────────────────────────────────────────
const catalogues = new Map();
const polarisTables = new Map();

export function registerCatalogue(locale, table) {
  catalogues.set(locale, table);
}
export function catalogueFor(locale) {
  return catalogues.get(locale) ?? null;
}
export function registerPolaris(locale, table) {
  polarisTables.set(locale, table);
}
/** Polaris's own strings (pagination, modals, date pickers) for a loaded locale, else null → the caller uses English. */
export function polarisFor(locale) {
  return polarisTables.get(locale) ?? null;
}
/** English is always loaded; another locale is loaded once its catalogue is registered. */
export function isLocaleLoaded(locale) {
  return locale === DEFAULT_UI_LOCALE || catalogues.has(locale);
}

const PLURAL_RE = /\{(\w+),\s*plural,\s*((?:=?\w+\s*\{[^{}]*\}\s*)+)\}/g;

function pluralCategory(locale, n) {
  try {
    return new Intl.PluralRules(locale).select(Number(n));
  } catch {
    return Number(n) === 1 ? "one" : "other";
  }
}

/** Fill `{name}` and `{n, plural, …}` in a catalogue value. Pure. */
export function interpolate(value, vars = {}, locale = DEFAULT_UI_LOCALE) {
  let s = String(value ?? "");
  s = s.replace(PLURAL_RE, (_m, name, forms) => {
    const n = vars[name];
    const table = {};
    for (const m of forms.matchAll(/(=?\w+)\s*\{([^{}]*)\}/g)) table[m[1]] = m[2];
    const exact = table[`=${n}`];
    const chosen = exact ?? table[pluralCategory(locale, n)] ?? table.other ?? "";
    return chosen.replace(/#/g, String(n));
  });
  s = s.replace(/\{(\w+)\}/g, (m, name) => (name in vars ? String(vars[name]) : m));
  return s;
}

/**
 * The translation function for a locale. Unknown key → the key itself (it IS
 * the English). A live locale whose catalogue is not loaded yet (the browser,
 * mid language switch) reads as English until the chunk arrives.
 */
export function createT(locale = DEFAULT_UI_LOCALE) {
  const loc = LIVE_UI_LOCALES.includes(locale) ? locale : DEFAULT_UI_LOCALE;
  const table = loc === DEFAULT_UI_LOCALE ? null : catalogueFor(loc);
  const t = (key, vars) => {
    const value = table?.[key] ?? key;
    return vars ? interpolate(value, vars, loc) : value;
  };
  t.locale = loc;
  t.number = (n, opts) => new Intl.NumberFormat(loc, opts).format(n);
  t.date = (d, opts = { day: "numeric", month: "long" }) => new Intl.DateTimeFormat(loc, opts).format(new Date(d));
  t.currency = (amount, currency = "USD") => new Intl.NumberFormat(loc, { style: "currency", currency }).format(amount);
  return t;
}

/**
 * English, always available: the default `t` of every pure util that builds
 * a merchant sentence, so a util called without one produces exactly the
 * English it produced before the layer existed — and its tests hold.
 */
export const enT = createT(DEFAULT_UI_LOCALE);

/** Server side: the locale from a request's URL (the embedded app keeps `locale` sticky). */
export function localeFromRequest(request) {
  try {
    return normaliseUiLocale(new URL(request.url).searchParams.get("locale"));
  } catch {
    return DEFAULT_UI_LOCALE;
  }
}

export const tForRequest = (request) => createT(localeFromRequest(request));

/**
 * Marks a string that lives outside any function (an options table, a plan
 * name) as a catalogue key WITHOUT translating it there — the use site calls
 * t(value) at render time. Identity at runtime; the extractor collects it.
 */
export const T = (s) => s;
export const tFor = (locale) => createT(normaliseUiLocale(locale));
