// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/subscriptions_update": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products/create": {
    params: {};
  };
  "/proxy/llms-full.txt": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/proxy/llms.txt": {
    params: {};
  };
  "/api/jobs-status": {
    params: {};
  };
  "/api/generate": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/plans-reconcile": {
    params: {};
  };
  "/app/products/:id": {
    params: {
      "id": string;
    };
  };
  "/app/collections": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/seo-audit": {
    params: {};
  };
  "/app/optimize": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/welcome": {
    params: {};
  };
  "/app/review": {
    params: {};
  };
  "/app/plans": {
    params: {};
  };
  "/app/setup": {
    params: {};
  };
  "/app/blog": {
    params: {};
  };
  "/app/blog/posts": {
    params: {};
  };
  "/app/jobs": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/subscriptions_update" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/products/create" | "/proxy/llms-full.txt" | "/webhooks/shop/redact" | "/proxy/llms.txt" | "/api/jobs-status" | "/api/generate" | "/api/health" | "/auth/login" | "/auth/*" | "/app" | "/app/plans-reconcile" | "/app/products/:id" | "/app/collections" | "/app/analytics" | "/app/seo-audit" | "/app/optimize" | "/app/products" | "/app/settings" | "/app/welcome" | "/app/review" | "/app/plans" | "/app/setup" | "/app/blog" | "/app/blog/posts" | "/app/jobs";
  };
  "routes/webhooks.app.subscriptions_update.jsx": {
    id: "routes/webhooks.app.subscriptions_update";
    page: "/webhooks/app/subscriptions_update";
  };
  "routes/webhooks.customers.data_request.jsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.jsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products.create.jsx": {
    id: "routes/webhooks.products.create";
    page: "/webhooks/products/create";
  };
  "routes/proxy.llms-full[.]txt.jsx": {
    id: "routes/proxy.llms-full[.]txt";
    page: "/proxy/llms-full.txt";
  };
  "routes/webhooks.shop.redact.jsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/proxy.llms[.]txt.jsx": {
    id: "routes/proxy.llms[.]txt";
    page: "/proxy/llms.txt";
  };
  "routes/api.jobs-status.jsx": {
    id: "routes/api.jobs-status";
    page: "/api/jobs-status";
  };
  "routes/api.generate.jsx": {
    id: "routes/api.generate";
    page: "/api/generate";
  };
  "routes/api.health.jsx": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/plans-reconcile" | "/app/products/:id" | "/app/collections" | "/app/analytics" | "/app/seo-audit" | "/app/optimize" | "/app/products" | "/app/settings" | "/app/welcome" | "/app/review" | "/app/plans" | "/app/setup" | "/app/blog" | "/app/blog/posts" | "/app/jobs";
  };
  "routes/app.plans-reconcile.jsx": {
    id: "routes/app.plans-reconcile";
    page: "/app/plans-reconcile";
  };
  "routes/app.products_.$id.jsx": {
    id: "routes/app.products_.$id";
    page: "/app/products/:id";
  };
  "routes/app.collections.jsx": {
    id: "routes/app.collections";
    page: "/app/collections";
  };
  "routes/app.analytics.jsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.seo-audit.jsx": {
    id: "routes/app.seo-audit";
    page: "/app/seo-audit";
  };
  "routes/app.optimize.jsx": {
    id: "routes/app.optimize";
    page: "/app/optimize";
  };
  "routes/app.products.jsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.welcome.jsx": {
    id: "routes/app.welcome";
    page: "/app/welcome";
  };
  "routes/app.review.jsx": {
    id: "routes/app.review";
    page: "/app/review";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.plans.jsx": {
    id: "routes/app.plans";
    page: "/app/plans";
  };
  "routes/app.setup.jsx": {
    id: "routes/app.setup";
    page: "/app/setup";
  };
  "routes/app.blog.jsx": {
    id: "routes/app.blog";
    page: "/app/blog" | "/app/blog/posts";
  };
  "routes/app.blog.posts.jsx": {
    id: "routes/app.blog.posts";
    page: "/app/blog/posts";
  };
  "routes/app.jobs.jsx": {
    id: "routes/app.jobs";
    page: "/app/jobs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.subscriptions_update": typeof import("./app/routes/webhooks.app.subscriptions_update.jsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.products.create": typeof import("./app/routes/webhooks.products.create.jsx");
  "routes/proxy.llms-full[.]txt": typeof import("./app/routes/proxy.llms-full[.]txt.jsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.jsx");
  "routes/proxy.llms[.]txt": typeof import("./app/routes/proxy.llms[.]txt.jsx");
  "routes/api.jobs-status": typeof import("./app/routes/api.jobs-status.jsx");
  "routes/api.generate": typeof import("./app/routes/api.generate.jsx");
  "routes/api.health": typeof import("./app/routes/api.health.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.plans-reconcile": typeof import("./app/routes/app.plans-reconcile.jsx");
  "routes/app.products_.$id": typeof import("./app/routes/app.products_.$id.jsx");
  "routes/app.collections": typeof import("./app/routes/app.collections.jsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.jsx");
  "routes/app.seo-audit": typeof import("./app/routes/app.seo-audit.jsx");
  "routes/app.optimize": typeof import("./app/routes/app.optimize.jsx");
  "routes/app.products": typeof import("./app/routes/app.products.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.welcome": typeof import("./app/routes/app.welcome.jsx");
  "routes/app.review": typeof import("./app/routes/app.review.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.plans": typeof import("./app/routes/app.plans.jsx");
  "routes/app.setup": typeof import("./app/routes/app.setup.jsx");
  "routes/app.blog": typeof import("./app/routes/app.blog.jsx");
  "routes/app.blog.posts": typeof import("./app/routes/app.blog.posts.jsx");
  "routes/app.jobs": typeof import("./app/routes/app.jobs.jsx");
};