-- Phase 2 item 2.4 — one dismissible explainer banner on Home.
--
-- The app previously explained itself to an already-installed merchant three
-- times on the Home screen and rendered the same gradient marketing strip on
-- six routes. That is replaced by a single Polaris banner, and a banner that
-- cannot be dismissed permanently is just a banner.
--
-- Dismissal is per shop rather than per browser: localStorage would bring it
-- back on the merchant's phone, and on their laptop the next time they cleared
-- site data.
--
-- Nullable with no default and no backfill, so this is additive: every existing
-- row reads NULL, which means "not dismissed", which is the correct state for a
-- banner nobody has seen yet.
ALTER TABLE "GrowthState" ADD COLUMN "geoNoteDismissedAt" TIMESTAMP(3);

-- Phase 2 item 2.6 — "Publish without review", one switch, in Settings.
--
-- Auto-publish was exposed in five places: a checkbox on the product page, one
-- in the Products bulk panel, one in the Generate All modal, and two on
-- Optimise. The bulk panel submitted with NO confirmation at all, and a bug in
-- the product page skipped the confirm on five of its seven generate paths.
--
-- Merchants were told on the App Store listing that nothing goes live until
-- they approve it. That has to be literally true unless they deliberately
-- turned it off, and a promise that depends on which of five checkboxes was
-- last ticked is not a promise.
--
-- Default false: an existing shop that had ticked a per-run box has NOT opted
-- into publishing without review, so it must not inherit one.
ALTER TABLE "BrandVoice" ADD COLUMN "publishWithoutReview" BOOLEAN NOT NULL DEFAULT false;
