/**
 * Phase 2 items 2.4 and 2.5 — no marketing inside the app, and Polaris only.
 *
 * Built for Shopify reviewers reject custom chrome, so "we removed the
 * gradients" has to stay true after the next person is in a hurry. These are
 * the standing checks.
 *
 * The marketing half matters for a different reason. Two of the claims that
 * were shipped are not merely unverifiable:
 *
 *   - a tip promised "Repurpose posts into social media captions with the Blog
 *     Generator" — the Blog Generator has no such feature;
 *   - GeoValueBanner's own header comment recorded that Google retired FAQ rich
 *     results on 7 May 2026 and that evidence for JSON-LD-only markup helping AI
 *     citation "is thin", and the component then shipped those claims on seven
 *     screens.
 *
 * Both are gone. The assertions below stop them coming back by their words.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { join, sep } from "node:path";

const ROUTES = "app/routes";
const COMPONENTS = "app/components";

/** Every shipped UI file. Not tests, not server-only utils. */
function uiFiles() {
  const out = [];
  for (const dir of [ROUTES, COMPONENTS]) {
    for (const f of readdirSync(dir)) {
      // join() gives backslashes on Windows and the assertions compare paths.
      if (f.endsWith(".jsx")) out.push(join(dir, f).split(sep).join("/"));
    }
  }
  return out;
}

const read = (f) => readFileSync(f, "utf8");
const code = (f) =>
  read(f)
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^[ \t]*\/\/.*$/gm, "");

/**
 * Phase 3 owns these two routes and the brief says to leave them alone until
 * then, so they are excluded by name rather than silently passing.
 */
const PHASE_3 = ["app.welcome.jsx", "app.setup.jsx"];
const shipped = () => uiFiles().filter((f) => !PHASE_3.some((p) => f.endsWith(p)));

describe("2.4 — the marketing components are gone, with no references left", () => {
  it("neither component file exists", () => {
    expect(existsSync("app/components/GeoValueBanner.jsx")).toBe(false);
    expect(existsSync("app/components/ContentBenefits.jsx")).toBe(false);
  });

  it("nothing imports or renders them — the grep proof", () => {
    const offenders = uiFiles().filter((f) => /GeoValueBanner|ContentBenefits/.test(read(f)));
    expect(offenders).toEqual([]);
  });

  it("one explainer banner survives, and it is on Home only", () => {
    const withBanner = shipped().filter((f) => read(f).includes("Written for Google and for AI search"));
    expect(withBanner).toEqual(["app/routes/app._index.jsx"]);
  });

  it("the explainer can be dismissed for good, not just for this page view", () => {
    // A banner that returns on every load is not dismissible. The flag is
    // stored per shop, so it also stays dismissed on the merchant's phone.
    const src = read("app/routes/app._index.jsx");
    expect(src).toMatch(/geoNoteDismissed/);
    expect(src).toMatch(/geoNoteDismissedAt/);
    expect(read("prisma/schema.prisma")).toMatch(/geoNoteDismissedAt\s+DateTime\?/);
  });
});

describe("2.4 — the claims that were not true", () => {
  const BANNED = [
    ["world-class standard", "an unverifiable quality claim"],
    ["keeps your SEO rankings strong", "an unverifiable ranking claim"],
    ["Longer posts rank better", "an unverifiable ranking claim"],
    ["ideal search visibility", "an unverifiable ranking claim"],
    ["Repurpose posts into social media captions", "a promise for a feature that does not exist"],
    ["difference between being found and being cited", "marketing, not information"],
    ["Generated by premium AI", "a vendor claim aimed at somebody who has already installed"],
    ["Start driving organic traffic", "a second empty state stacked under the real one"],
  ];

  for (const [phrase, why] of BANNED) {
    it(`no screen says "${phrase}" — ${why}`, () => {
      const offenders = shipped().filter((f) => read(f).includes(phrase));
      expect(offenders).toEqual([]);
    });
  }
});

describe("2.5 — Polaris only", () => {
  it("no route or component imports lucide-react", () => {
    expect(uiFiles().filter((f) => read(f).includes("lucide-react"))).toEqual([]);
  });

  it("lucide-react is not a dependency at all", () => {
    const pkg = JSON.parse(read("package.json"));
    expect(pkg.dependencies?.["lucide-react"]).toBeUndefined();
    expect(pkg.devDependencies?.["lucide-react"]).toBeUndefined();
  });

  it("package.json and the lock file agree — npm ci would not fail", () => {
    // Removing a dependency from package.json without regenerating the lock
    // makes `npm ci` refuse to run, which takes CI down on the next push.
    const lock = read("package-lock.json");
    expect(lock).not.toMatch(/"node_modules\/lucide-react"/);
  });

  it("no gradient, dark hero or custom shadow survives", () => {
    for (const f of shipped()) {
      const src = code(f);
      expect(src, `${f} has a gradient`).not.toMatch(/linear-gradient/);
      expect(src, `${f} has a custom shadow`).not.toMatch(/boxShadow/);
    }
  });

  it("no route injects a <style> element into the DOM", () => {
    // app.jsx declared two @keyframes at runtime; app.blog.jsx declared fifteen
    // typography rules that competed with Polaris.
    for (const f of shipped()) {
      expect(code(f), `${f} injects a stylesheet`).not.toMatch(/<style>/);
    }
  });

  it("no div pretends to be a button", () => {
    for (const f of shipped()) {
      expect(code(f), `${f} has a role="button" div`).not.toMatch(/role="button"/);
    }
  });

  it("the pages the brief named carry no inline styles at all", () => {
    for (const f of [
      "app/routes/app.jsx",
      "app/routes/app.settings.jsx",
      "app/routes/app.review.jsx",
      "app/routes/app.results.jsx",
      "app/components/UpgradePrompt.jsx",
    ]) {
      const styles = (code(f).match(/style=\{\{/g) || []).length;
      // app.jsx keeps exactly one: padding on the nav logo slot, which is a
      // Shopify web-component slot rather than app chrome.
      expect(styles, `${f} has ${styles} inline styles`).toBeLessThanOrEqual(
        f.endsWith("app.jsx") ? 1 : 0,
      );
    }
  });

  it("no emoji is used as an interface element", () => {
    // Not a style preference: a bare glyph in a Badge has no text alternative,
    // and the SEO Audit table rendered roughly 400 of them on a 100-product
    // store with nothing for a screen reader to announce.
    const EMOJI = /[\u{1F300}-\u{1FAFF}⚡⭐⚠✏\u{1F389}\u{1F512}]/u;
    for (const f of shipped()) {
      const hit = code(f).match(EMOJI);
      expect(hit?.[0], `${f} still uses ${hit?.[0]} in the interface`).toBeUndefined();
    }
  });

  it("no button label ends in an arrow", () => {
    for (const f of shipped()) {
      expect(code(f), `${f} has an arrow in a label`).not.toMatch(/[→←]/);
    }
  });
});

describe("2.5 — mobile.css stops fighting Polaris", () => {
  // Comments are stripped: this file explains at length WHICH Polaris internals
  // it stopped overriding, and naming them is the point of the explanation.
  const css = readFileSync("app/mobile.css", "utf8").replace(/\/\*[\s\S]*?\*\//g, "");

  it("overrides no private Polaris internals", () => {
    // These class names are generated and unversioned. A rule that targets them
    // stops applying silently on a Polaris upgrade, which is the worst kind of
    // regression: nothing errors, the layout just quietly breaks.
    for (const sel of [
      ".Polaris-DataTable__ScrollContainer",
      ".Polaris-Layout__Section--oneThird",
      ".Polaris-TextField__Input",
      ".Polaris-Page-Header__RightAlign",
      ".Polaris-Modal-Dialog__Modal",
      ".Polaris-Tabs__Wrapper",
    ]) {
      expect(css, `still overrides ${sel}`).not.toContain(sel);
    }
  });

  it("uses !important only where it is genuinely correct", () => {
    // Reduced motion is the one case: the whole point is to beat any animation
    // the page declares. Everything else was patching layout Polaris does.
    const lines = css.split("\n").filter((l) => l.includes("!important") && !l.trim().startsWith("*"));
    expect(lines.length).toBeLessThanOrEqual(4);
    for (const l of lines) {
      expect(l).toMatch(/animation|transition|scroll-behavior/);
    }
  });

  it("the touch-target minimum is not undone three lines later", () => {
    // The old rule set 44px on every button, then dropped slim and micro back
    // to 36px — carving out exactly the buttons most easily mis-tapped. It was
    // also scoped to <=768px, so it did not apply on a touch laptop.
    expect(css).toMatch(/@media \(pointer: coarse\)/);
    expect(css).not.toMatch(/min-height:\s*36px/);
  });

  it("declares no selector whose markup no longer exists", () => {
    const attrs = [...css.matchAll(/\[data-cc-[a-z-]+\]/g)].map((m) => m[0]);
    const markup = uiFiles().map(read).join("\n");
    for (const a of attrs) {
      const name = a.slice(1, -1);
      expect(markup, `${a} is styled but nothing renders it`).toContain(name);
    }
  });
});
